export const CREATE_CONFIGURATION = 'CREATE_CONFIGURATION';
export const FETCH_CONFIGURATIONS = 'FETCH_CONFIGURATIONS';
export const FETCH_CONFIGURATION = 'FETCH_CONFIGURATION';
export const DELETE_CONFIGURATION = 'DELETE_CONFIGURATION';
export const EDIT_CONFIGURATION = 'EDIT_CONFIGURATION';